apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- storageclass.yaml
- sealedsecret.yaml
- ingress.yaml

helmCharts:
- name: loki
  repo: https://grafana.github.io/helm-charts
  version: 6.49.0
  releaseName: monitoring
  namespace: monitoring
  valuesFile: loki-values.yaml
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 10.4.0
  releaseName: monitoring
  namespace: monitoring
  valuesFile: grafana-values.yaml
