apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
        app.kubernetes.io/name: redis-test-app
    spec:
      containers:
      - name: test-redis-python
        image: python:3.14-alpine
        env:
        - name: TZ
          value: Europe/Brussels
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-redis-secret
              key: redis-password
        command:
        - sh
        - -c
        - echo 'Install Python dependencies:' && pip install redis prometheus-client && python /app/main.py
        ports:
        - containerPort: 8000
          name: metrics
        volumeMounts:
        - name: script-volume
          mountPath: /app
        - name: cache-volume
          mountPath: /cache
        imagePullPolicy: IfNotPresent
      volumes:
      - name: script-volume
        configMap:
          name: redis-python-script
      - name: cache-volume
        emptyDir:
          sizeLimit: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-deployment-service
spec:
  selector:
    app: test
  ports:
  - port: 8000
    targetPort: metrics
    name: metrics
