apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
- namespace.yaml
- storageclass.yaml
- sealedsecret.yaml
- configmap.yaml
- deployment.yaml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 24.1.0
  releaseName: redis
  namespace: redis
  includeCRDs: true
  valuesFile: values.yaml

patches:
# Annotate Service to be exposed via Tailscale
- target:
    version: v1
    kind: Service
    name: redis-master
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-master
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "redis-master-raspberrypi"
# Annotate Service to be exposed via Tailscale
- target:
    version: v1
    kind: Service
    name: redis-replicas
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-replicas
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "redis-replicas-raspberrypi"
