apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-redis-secret
spec:
  encryptedData:
    redis-password: AgAViwe2eUClYbeYMH+85ZsUdEdnGNi7NGV4VgXEyM03FmKShsAJJJW25ow5F+dNdPGQlV/Y2AdYZGlFTqmhV3AhIleQHje/g8n9DGTLcUhFVJRap2MYhctVrSbFU/P3rFcMy3YKXDq1OXqJH6Ec0JUict8tsHkKmaNuLyfOqK26FSuhYnMdErwuVmT7D+ck83nTG1DlNaIZ2mspxeeXz8GlDRdhR/QBkNKaFXoRS2riAl9zth0ogOrxxmDqWG2ZhMaGi3QrHaKOXfYTYnWF1MwQcsvhbsgFSOMmFp5QWvjl+uaKV9JiM5erbAAbhWe67aPDnaNeg5UVsBOMcYwSvDE0KGzj8SIJEK8JYs2x3b5UYlX11sVwu9c+VitNoGhsJvU6x+YO5B4olDDeGRx3BG+AHdNrFr/dD8f4jnz/V9BQzlnvW6q2wi1cXQsJGa6feywuWrX2uwmcpoJHNaFdpAwiCRqRzwW4H2r+aUXfA9+QF6UCTvIigAUSvzvo4Ocx9o2nKIT2KEL4pqfRvIZDw7IFaNKGawiWimHJc+VZOrvifh7fK0g1hSytRZXbRtdAhOLykz7W+uINtI47TPDqXYHVnEZaS7LnE7a9msXtTbi23+3JgHyLfHwcGqCPf3eAQE1c2+2hvznv1ojGxkDYs/1jcjJd0KkPsa5NuIrRhfEOOAg0kkvjBIZFvJOssHALHikvXEFE5GNXvcQ=
