apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-redis-monitor
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - redis
  selector:
    matchLabels:
      app: test-redis-service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
