apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-redis-monitor
spec:
  namespaceSelector:
    matchNames:
    - redis
  selector:
    matchLabels:
      app: test-redis-service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test-redis-monitor
spec:
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorSelector:
    matchLabels:
      app: test
