kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
reclaimPolicy: Delete
