service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.1.20

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`raspberrypi5.local`)
    entryPoints:
    - web

ingressClass:
  isDefaultClass: false

logs:
  access:
    enabled: true
