apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
- namespace.yaml
- storageclass.yaml
- sealedsecrets.yaml
- configmap.yaml
- deployment.yaml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 23.2.12
  releaseName: redis
  namespace: redis
  includeCRDs: true
  valuesFile: values.yaml

patches:
# JSON patch example
- target:
    version: v1
    kind: Service
    name: redis-master
  patch: |-
    - op: add
      path: /metadata/annotations
      value: {}
    - op: add
      path: /metadata/annotations/tailscale.com~1expose
      value: "true"
# Strategic merge patch example
- target:
    version: v1
    kind: Service
    name: redis-replicas
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-replicas
      annotations:
        tailscale.com/expose: "true"
