apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
- namespace.yaml
- storageclass.yaml
- sealedsecrets.yaml
- configmap.yaml
- pod.yaml
- loadbalancer.yaml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 23.2.12
  releaseName: redis
  namespace: redis
  includeCRDs: true
  valuesFile: values.yaml
