apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis

resources:
- namespace.yaml
- storageclass.yaml
- sealedsecrets.yaml
- configmap.yaml
- pod.yaml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 23.2.12
  releaseName: redis
  namespace: redis
  includeCRDs: true
  valuesFile: values.yaml

patches:
- target:
    kind: Service
    name: redis-master
  patch: |-
    - op: add
      path: /metadata/annotations
      value: {}
    - op: add
      path: /metadata/annotations/tailscale.com~1expose
      value: "true"
- target:
    kind: Service
    name: redis-replicas
  patch: |-
    - op: add
      path: /metadata/annotations
      value: {}
    - op: add
      path: /metadata/annotations/tailscale.com~1expose
      value: "true"
