global:
  defaultStorageClass: "longhorn-redis"

master:
  persistence:
    size: 200Mi

replica:
  persistence:
    size: 100Mi

auth:
  sentinel: false
  existingSecret: my-redis-secret
  existingSecretPasswordKey: redis-password
