global:
  defaultStorageClass: "longhorn-redis"

master:
  persistence:
    size: 200Mi

replica:
  persistence:
    size: 100Mi

auth:
  existingSecret: my-redis
  existingSecretPasswordKey: redis-password
