apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: fluent/fluent-bit
  repo: https://fluent.github.io/helm-charts
  version: 0.54.0
  releaseName: fluentbit
  namespace: fluentbit
  valuesFile: values.yaml
