apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: fluentd
  repo: https://fluent.github.io/helm-charts
  version: 0.5.3
  releaseName: fluentbit
  namespace: fluentbit
  valuesFile: values.yaml
