# values.yaml voor fluentd helm chart
fileConfigs:
  01_sources.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      read_from_head true
      <parse>
        @type cri
      </parse>
    </source>

  02_filters.conf: |
    <filter kube.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <filter kube.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern /^(argocd)$/
      </regexp>
    </filter>

  03_outputs.conf: |
    <match kube.**>
      @type stdout
    </match>
