apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test01

resources:
- namespace.yaml
- blue-app.yaml
- green-app.yaml
- ingress.yaml
#- cert-manager-issuers.yaml
#- keda-scaled-object.yaml
- cluster-info.yaml
- gateway-api-traefik.yaml

labels:
- pairs:
    app.kubernetes.io/name: blue-green
    app.kubernetes.io/instance: blue-green-instance01
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: blue-green

buildMetadata: [managedByLabel]

images:
- name: nginx
  newTag: 1.29.3-alpine
