apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-ingress

resources:
- namespace.yaml

helmCharts:
- name: nginx-ingress
  repo: oci://ghcr.io/nginx/charts
  version: 2.4.4
  releaseName: nginx-ingress
  namespace: nginx-ingress
  includeCRDs: true
  valuesFile: values.yaml
