githubConfigUrl: "https://github.com/wim-vdw/gh-actions-npm-cache-test"
githubConfigSecret: "my-github-pat-token"
controllerServiceAccount:
  name: actions-runner-controller-gha-rs-controller
  namespace: arc-systems
minRunners: 1
maxRunners: 5
containerMode:
  type: "kubernetes-novolume"
