apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-github-pat-token
spec:
  encryptedData:
    github_token: AgDLmEfMoh+j9ON+3/wQiRRy2a52aXc0hVCTOcnwY53IPT+XN/gAMPDC2MHhlCNtGXzkw3KwXif5Cr7u890YDrGyp3Rc92zvv534aAIaO0eb3IweJ4crM8HLIkUkNZikZ6pNDILa5gYNd5Lu28DiTqywyApVx0FHFB+QFUmZDeQiHtemgbdu3zKvJSPCOn4U27Cp3eTvHoJDtY81SsWHhLZFgle9N/grGvN70aTvE8juLX/SlSefmwIG/dwTVAu9blg3HczVWq1WZIjsxzCB9qu+BI6e5fN27CcQOgfN/KHFbblsd27ydWy3oaopiIqC7YmND08E8eguor3fNMTlR5oiAujT93IqEosrdVL3bWxAcwuWo9CXTpP4qHZ3EBbtWOy/ICXuzAhJFoj0zGOBZmVXU2qT+74ufV1wkCjBfbS9FfiGMVA7AOKVL148qjdL6Fg63nX2En3L2rgcEHVX8Bf8cmLYdpm2l2r0B+T/rQEiZ09qeimAqatALmtItKNl45hkmlSikxi3jVZvcCm+1xEDyxiXHvMVADEcy8RrRr4Ut9lxKrC5D4hHTeVReZLpNaQexmIdle7Hc7U+7FbcIVPWFe1zkuAoZQsorf1TpQT55YM9TNPjdTaWee6RfGi6YIDhHfADZR/DtUePx5QLgzs2GgrHzFaJMW528agJTdLhR4AZounBFpnf47TALqUjGRsVjVQL38I55AAXhrZ1ByNmO6/C79+1HRJx5zE7JihRDWWfYXVMr4ht
